---
apiVersion: v1
kind: Service
metadata:
  name: description-reading
  namespace: imanicipation
  labels:
    app: description-reading
    tier: backend
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: description-reading
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: description-reading
  namespace: imanicipation
spec:
  selector:
    matchLabels:
      app: imani-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: imani-service
        tier: backend
    spec:
      containers:
        - name: imani-service
          image: registry.hub.docker.com/imanileemans/description-r
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
