version: '3.8'

services:
  description-r:
    image: description-r
    container_name: description-r
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://455181:83ZMrlRZAIbcSTqM@project.uah3szf.mongodb.net/?retryWrites=true&w=majority
      SPRING_DATA_MONGODB_DATABASE: IndvProject
    networks:
      - spring-net

networks:
  spring-net:
    name: spring-net
    driver: bridge

volumes:
  userdata: